// mockData.js - 模拟监护人消息数据

export const mockGuardians = [
  {
    id: 1,
    name: "李建国",
    relation: "爸爸",
    avatarType: "image",
    avatar: "/icons/avatar2.jpg",
    phone: "138****0001",
    status: "online",
    level: "full",
    lastActive: "刚刚",
    lastTime: "刚刚",
    lastMsg: "收到系统预警：检测到可疑链接，请注意安全！",
    unread: 2,
    notifications: { app: true, sms: true, phone: false },
  },
  {
    id: 2,
    name: "王淑芬",
    relation: "妈妈",
    avatarType: "image",
    avatar: "/icons/avatar3.jpg",
    phone: "138****0002",
    status: "online",
    level: "full",
    lastActive: "5分钟前",
    lastTime: "5分钟前",
    lastMsg: "好的，我知道了，注意安全",
    unread: 0,
    notifications: { app: true, sms: true, phone: false },
  },
  {
    id: 3,
    name: "张明远",
    relation: "班主任",
    avatarType: "image",
    avatar: "/icons/avatar4.jpg",
    phone: "138****0003",
    status: "offline",
    level: "limited",
    lastActive: "昨天",
    lastTime: "昨天",
    lastMsg: "关于校园安全教育的通知...",
    unread: 1,
    notifications: { app: true, sms: false, phone: false },
  },
  {
    id: 4,
    name: "陈立",
    relation: "叔叔",
    avatarType: "text",
    avatar: "陈",
    phone: "137****7777",
    status: "online",
    level: "full",
    lastActive: "1小时前",
    lastTime: "1小时前",
    lastMsg: "晚上一起吃饭吗？",
    unread: 0,
    notifications: { app: true, sms: true, phone: true },
  },
  {
    id: 5,
    name: "刘阿姨",
    relation: "阿姨",
    avatarType: "text",
    avatar: "刘",
    phone: "139****5555",
    status: "offline",
    level: "limited",
    lastActive: "昨天",
    lastTime: "昨天",
    lastMsg: "周末来家里玩啊",
    unread: 0,
    notifications: { app: true, sms: false, phone: false },
  },
  {
    id: 6,
    name: "王老师",
    relation: "数学老师",
    avatarType: "text",
    avatar: "王",
    phone: "136****8888",
    status: "offline",
    level: "limited",
    lastActive: "3天前",
    lastTime: "3天前",
    lastMsg: "作业已布置，请查收",
    unread: 0,
    notifications: { app: true, sms: false, phone: false },
  },
];

// 模拟新消息通知
export const mockNewMessage = {
  id: 7,
  name: "系统通知",
  relation: "系统",
  avatarType: "text",
  avatar: "系",
  phone: "",
  status: "online",
  level: "full",
  lastActive: "刚刚",
  lastTime: "刚刚",
  lastMsg: "您有一条新的风险预警，请及时查看",
  unread: 1,
};
