// homeCaseData.js — 首页右侧滚动卡片数据（攻击/防御主题）

export const caseData = {
  line1: [
    {
      score: "0.92",
      time: "2026-06-15",
      category: "AI深伪语音",
      title: "声纹克隆攻击：TTS 合成音频绕过身份验证",
      source: "安全研究团队",
      readCount: "3.1k",
      confidenceReason: "Wav2Vec2-XLSR 检测音频深伪分 r_a=0.92，频谱纹理异常，命中 IOC synthetic_voice_score>0.7，ATT&CK T1586",
      text: "攻击者收集目标语音样本，使用 TTS 声纹克隆技术合成高度逼真的模拟语音，随后冒充受害人熟人实施欺骗。VeriTide 深伪检测输出音频风险分 r_a=0.92，意图分解识别权威冒充+凭证窃取双重意图，置信度 0.91。防御：不信任陌生号码的语音转账请求，与家人预设语音验证暗语。",
      imageUrl: "icons/语音合成.png",
    },
    {
      score: "0.87",
      time: "2026-06-14",
      category: "权威身份冒充",
      title: "冒充公检法攻击链：三阶段社会工程学分析",
      source: "国家网络安全通报中心",
      readCount: "2.8k",
      confidenceReason: "识别攻击意图单元 3 个，置信度均超 0.85，killChain 标签命中已知模板，ATT&CK T1656，证据引用 REF-1 REF-2",
      text: "三阶段攻击链：建立可信（伪造警方通缉令）→ 隔离施压（要求保密制造紧迫感）→ 凭证窃取（要求转账至安全账户）。VeriTide 研判：BLOCK，风险分 0.87，意图分解命中权威冒充(0.92)、紧迫施压(0.88)、凭证窃取(0.97)。",
      imageUrl: "icons/冒充公检法.png",
    },
    {
      score: "0.73",
      time: "2026-06-13",
      category: "钓鱼截图攻击",
      title: "伪造官方通知截图：图像篡改特征检测",
      source: "安全研究团队",
      readCount: "1.9k",
      confidenceReason: "OCR 版面分析识别伪造徽标，图像深伪 r_i=0.73，存在像素级拼接痕迹，ATT&CK T1566",
      text: "攻击者发送伪造银行安全通知或政务公告截图，图片内嵌二维码引导访问钓鱼页面。VeriTide 图像检测 r_i=0.73，发现徽标边缘锯齿与字体像素混淆，OCR 提取 URL 命中 IOC 钓鱼域名规则。防御：不扫描来源不明的二维码，通过官方 App 直接核实。",
      imageUrl: "icons/短信.jpg",
    },
  ],
  line2: [
    {
      score: "0.81",
      time: "2026-06-12",
      category: "深伪视频攻击",
      title: "AI 换脸视频通话：实时深伪绕过人脸核验",
      source: "安全研究实验室",
      readCount: "4.2k",
      confidenceReason: "视频深伪分 r_v=0.81，帧间闪烁伪影，融合分 r_f=0.79，音视频跨模态一致性异常，ATT&CK T1598",
      text: "攻击者使用实时深伪技术在视频通话中替换面部，冒充受害人亲友或机构工作人员。VeriTide 检测 r_v=0.81，发现帧间闪烁伪影和边缘模糊，融合分析 r_f=0.79，音视频一致性异常。防御：通话中要求对方做随机动作，重要决策不在视频通话中做出。",
      imageUrl: "icons/AI换脸诈骗.webp",
    },
    {
      score: "0.65",
      time: "2026-06-11",
      category: "社会工程学",
      title: "长周期情感操控：认知渗透与投资诱导分析",
      source: "威胁情报分析组",
      readCount: "3.5k",
      confidenceReason: "情感操控意图单元持续周期大于 30 天，ATT&CK T1534 内部鱼叉式网络钓鱼，投资诱导 IOC 命中 6 条",
      text: "攻击者在社交平台伪装潜在恋人，长期经营情感关系后引导加入虚假投资平台，初期小额盈利制造幻觉，最终诱导大额投入后平台消失。DSCP 意图分解：情感建立(0.78)→信任强化(0.82)→虚假盈利(0.91)→大额诱导(0.95)。",
      imageUrl: "icons/杀猪盘.jpeg",
    },
    {
      score: "0.58",
      time: "2026-06-10",
      category: "信息窃取利用",
      title: "数据泄露后精准攻击：个人信息被滥用分析",
      source: "数据安全研究中心",
      readCount: "2.1k",
      confidenceReason: "攻击者掌握受害人真实姓名住址等精确信息，符合数据泄露后精准攻击特征，DLP 检测 PHONE x3 ID_CARD x1，ATT&CK T1589",
      text: "攻击者通过黑市购买泄露数据，掌握姓名、手机、身份证号、住址等信息，实施高精准度针对性攻击。知道你的信息不代表可信。VeriTide DLP 脱敏：PHONE x3、ID_CARD x1，全部本地替换，原始数据未上传。",
      imageUrl: "icons/电信诈骗.jpg",
    },
  ],
  line3: [
    {
      score: "0.95",
      time: "2026-06-09",
      category: "多模态融合攻击",
      title: "音视图文四路联合攻击：最高置信度检测案例",
      source: "VeriTide 实验室",
      readCount: "5.6k",
      confidenceReason: "四路深伪分数均超阈值，5 个攻击意图单元全部识别，路由直达 BLOCK，证据网络节点 7 个无幻觉引用",
      text: "最高复杂度多模态攻击样本：深伪音频+深伪视频+伪造截图+精心话术四路协同。r_i=0.88，r_a=0.93，r_v=0.91，r_f=0.95。路由 FAST→EXPAND→DEEP→BLOCK，意图单元 5/5，证据网络引用 7 条。展示了单路检测可能漏判，融合分析才能揭示完整攻击链的核心价值。",
      imageUrl: "icons/语音诈骗.png",
    },
    {
      score: "0.44",
      time: "2026-06-08",
      category: "低风险通过",
      title: "正常业务通话：VeriTide 低误报验证案例",
      source: "VeriTide 测试集",
      readCount: "0.9k",
      confidenceReason: "四路深伪分数均低于阈值，无攻击意图单元识别，路由 FAST 42ms 完成，策略动作 PASS",
      text: "正常业务通话样本，验证 VeriTide 低误报性能。r_i=0.06，r_a=0.11，r_f=0.09。路由 FAST，42ms 完成，0 个意图单元，策略动作 PASS。验证系统误报率低于 4%，正常通话不会被误判拦截，体现 Conformal Prediction 置信校准精确性。",
      imageUrl: "icons/客服.jpg",
    },
    {
      score: "0.79",
      time: "2026-06-07",
      category: "招聘类攻击",
      title: "虚假招聘攻击：伪造企业信息与合同分析",
      source: "就业安全研究组",
      readCount: "1.6k",
      confidenceReason: "OCR 识别合同水印伪造特征，图像深伪 r_i=0.67，ATT&CK T1566，IOC 命中 fake_employer_pattern",
      text: "攻击者发布高薪虚假招聘信息，诱导求职者提供身份信息后以培训费、保证金等名义实施攻击。VeriTide 图像检测 r_i=0.67，识别合同水印区域像素异常。防御：正规招聘不要求求职者先行付款，通过国家企业信用信息公示系统核实企业真实性。",
      imageUrl: "icons/招聘.jpg",
    },
  ],
};
