"""共享配置。"""

from .llm_config import DEFAULT_DASHSCOPE_MODEL, DEFAULT_LOCAL_MODEL_PATH, DEFAULT_LLM_PROVIDER

__all__ = [
    "DEFAULT_DASHSCOPE_MODEL",
    "DEFAULT_LOCAL_MODEL_PATH",
    "DEFAULT_LLM_PROVIDER",
]

